### ISSUE TITLE
Typo in README? `singleton` vs `isSingleton` option

### ISSUE THREAD

**Issue by zaim** [sergiolepore/Cation#10]
In the README, examples for singleton resources indicate to use the `singleton` option key.

But I believe in the source code, the singleton option is `isSingleton` instead?

See: https://github.com/sergiolepore/Cation/blob/master/src/cation.js#L156

**Comment by sergiolepore** [comment]
Doh! Sorry! I'm going to fix this ASAP. Thank you so much!

**Comment by sergiolepore** [comment]
@zaim fixed! Thank you!

PS: this release is dedicated to you. [v2.2.1](https://github.com/sergiolepore/Cation/releases/tag/v2.2.1)

**Comment by zaim** [comment]
LOL, thanks. Just want to help out since I've chosen Cation for my one of my side projects (will open source it soon). I chose it because (I think) it's the only DI/IOC lib that uses ES6 and Promises... that's a huge plus.

**Comment by sergiolepore** [comment]
@zaim thanks! :) Promises are awesome, and they look so nice while working with these lazy loaded dependencies.
The next feature I'm working on is the use of "sub containers" as a way to merge two or more different containers into one, or to isolate a groups of resources using a "namespace/subcontainer id" as the main reference.
For example:

```js
mainContainer.get('view:hbs_renderer')
mainContainer.get('view:ejs_renderer')

// or

mainContainer.getSubcontainer('view').get('hbs_renderer')
mainContainer.getSubcontainer('view').get('ejs_renderer')
```

I'll keep you updated on this, if you want.
