### ISSUE TITLE
What about browsers?

### ISSUE THREAD

**Issue by jifeon** [sergiolepore/Cation#8]
Hi! Great job, I like it. But I often use DI developing UI )) So my question is what about browsers? Any plans?

**Comment by sergiolepore** [comment]
Hi @jifeon! TBQH, I had plans to "pack" the `dist/` directory as an AMD module. Cation is not hard coupled to server side features, so maybe it can work in the browser.

I'll left this issue open and with a `Feature` label. If you have new suggestions, I'll be glad to hear them :smile:

**Comment by jifeon** [comment]
Cool! Thank you

**Comment by sergiolepore** [comment]
@jifeon you're welcome!

**Comment by sergiolepore** [comment]
I'm going to close this to put things in order for the new roadmap. I'm sorry, but no browser support is planned :confused:
