### ISSUE TITLE
Please update to 6to5 3.x

### ISSUE THREAD

**Issue by zaim** [sergiolepore/Cation#9]
I am using 6to5 3.3.0 in my own project, and when browserifying Cation, browserify includes 2 copies of `6to5/polyfill` (one 3.x, another 2.x which Cation is using). This is just a minor issue of saving bytes, but would be cool to have :)

**Comment by sergiolepore** [comment]
[Already working on it!](https://github.com/sergiolepore/Cation/tree/feature/6to5-v3) :smile: I'll be publishing the changes as soon as I can.
Thank you for your suggestion!

**Comment by sergiolepore** [comment]
@zaim cation@2.2.0 comes with 6to5 v3. Check it out!

**Comment by zaim** [comment]
Nice. Successfully upgraded :ok_hand:
